'use strict';
const CACHE_NAME='kaderplaner-v83-offline';
const CACHE_PREFIX='kaderplaner-';
const APP_SHELL=['./','./index.html','./manifest.webmanifest','./apple-touch-icon.png','./icon-192.png','./icon-512.png'];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);for(const path of APP_SHELL){try{const response=await fetch(path,{cache:'reload'});if(response.ok)await cache.put(path,response.clone())}catch(error){console.warn(path,error)}}if(!await cache.match('./index.html',{ignoreSearch:true}))throw new Error('index.html fehlt');await self.skipWaiting()})()));
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim()})()));
async function home(){const cache=await caches.open(CACHE_NAME);return await cache.match('./index.html',{ignoreSearch:true})||await cache.match('./',{ignoreSearch:true})||await cache.match('index.html',{ignoreSearch:true})}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith((async()=>{const cached=await home();if(cached){event.waitUntil(fetch(request).then(async response=>{if(response&&response.ok){const cache=await caches.open(CACHE_NAME);await cache.put('./index.html',response.clone());await cache.put('./',response.clone())}}).catch(()=>{}));return cached}try{return await fetch(request)}catch(error){return new Response('Bitte die App einmal online öffnen.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})}})());return}event.respondWith((async()=>{const cache=await caches.open(CACHE_NAME);const cached=await cache.match(request,{ignoreSearch:true});if(cached)return cached;try{const response=await fetch(request);if(response&&response.ok)await cache.put(request,response.clone());return response}catch(error){return new Response('',{status:503})}})())});
